# Generated by Django 5.1.4 on 2024-12-08 08:47

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=courses.models.handleUpload)),
                ('access', models.CharField(choices=[('any', 'Anyone'), ('email_required', 'Email Required')], default='any', max_length=20)),
                ('status', models.CharField(choices=[('pub', 'Published'), ('draft', 'Draft'), ('coming_soon', 'Coming Soon')], default='draft', max_length=20)),
            ],
        ),
    ]
